platform :ios, '10.0'
workspace 'NIM.xcworkspace'

abstract_target 'NIMDemo' do

    pod 'NIMSDK_LITE', '8.4.4'
    pod 'NERtcSDK', '4.0.7'
    pod 'YXAlog_iOS', '1.0.6'
  
    def common_pods
        pod 'Toast', '~> 3.0'
        pod 'YYImage'
        pod 'YYImage/WebP'
        pod 'SDWebImage', '~> 5.0.6'
        pod 'SDWebImageFLPlugin', '~> 0.3.0'
        pod 'M80AttributedLabel', '~> 1.9.9'
        pod 'TZImagePickerController', '~> 3.5.2'
    end
  
    target 'NIM' do
        project 'NIM.xcodeproj'
        pod 'FMDB', '~> 2.7.2'
        pod 'Reachability', '~> 3.2'
        pod 'CocoaLumberjack', '~> 3.2.1'
        pod 'SSZipArchive', '~> 1.8.1'
        pod 'SVProgressHUD', '~> 2.1.2'
        pod 'Fabric'
        pod 'Crashlytics'
        pod 'Masonry'
        common_pods
    end
    
    target 'NIMKit' do
        project '../NIMKit/NIMKit.xcodeproj'
        common_pods
    end
    
    target 'NERtcCallKit' do
        project '../NERtcCallKit/NERtcCallKit.xcodeproj'
    end
    
end

